server.servlet.context-path=/shared_shop
server.port=55000
spring.thymeleaf.cache=false

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:oracleadmin/MasterPass@xxxx.xxxx.ap-northeast-1.rds.amazonaws.com:1521:oracledb

###
###
 # Intermediate location of uploaded files.
spring.servlet.multipart.location=${user.dir}/temp
 # Max file size.
spring.servlet.multipart.max-file-size=1MB
 #
spring.servlet.multipart.max-request-size=10MB

server.servlet.register-default-servlet=true

