spring.profiles.active=local

#AWSへのデプロイ準備作業で有効にする
#spring.profiles.active=aws

spring.mail.host=smtp.gmail.com
spring.mail.port=587
 
spring.mail.username=sagarmatha603@gmail.com
spring.mail.password=ozbk yetf issn yxvr
 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
