#=======
#server.servlet.context-path=/shared_shop
#server.port=55000
#spring.thymeleaf.cache=false
#>>>>>>> 3f394fa91dec77b21c8ef388be846af7c5e8e7a8
#
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@SVSAIKEN:1521/PDBORCL
#spring.datasource.username=JAVAPRJ2026
#spring.datasource.password=JAVAPRJ2026
#



#ghrkoserver
#--------------------------------------------------------
server.servlet.context-path=/shared_shop
server.port=55000
spring.thymeleaf.cache=false

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/xepdb1
spring.datasource.username=halal_shop
spring.datasource.password=systemsss
#--------------------------------------------------------
##ghr ko server 


#kudratServer
#--------------------------------------------------------
#server.servlet.context-path=/shared_shop
#server.port=55000
#spring.thymeleaf.cache=false
#
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
#spring.datasource.username= shared_shop
#spring.datasource.password=systemsss
#--------------------------------------------------------
##ghr ko server 

##SQL譁・ｒ繧ｳ繝ｳ繧ｽ繝ｼ繝ｫ縺ｫ陦ｨ遉ｺ縺吶ｋ縺溘ａ縺ｮ險ｭ螳
#logging.level.org.hibernate.type.descriptor.sql=trace
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

###
###
 # Intermediate location of uploaded files.
spring.servlet.multipart.location=${user.dir}/temp
 # Max file size.
spring.servlet.multipart.max-file-size=1MB
 #
spring.servlet.multipart.max-request-size=10MB

server.servlet.register-default-servlet=true

